on:
  push:
  schedule:
  - cron:  '0 7 * * SUN'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nixPath:
          - nixpkgs=channel:nixos-unstable
          - nixpkgs=channel:nixpkgs-unstable
          - nixpkgs=channel:nixos-25.05
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: "${{ matrix.nixPath }}"
    - name: Show nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - name: Setup cachix
      uses: cachix/cachix-action@v16
      with:
        name: ${{ secrets.CACHIX_CACHE }}
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Install nix-build-uncached
      run: |
        nix profile install nixpkgs#nix-build-uncached
    - name: Build nix packages
      run: |
        nix-build-uncached ci.nix -A cacheOutputs
